### ISSUE TITLE
Should this package exist?

### ISSUE THREAD

**Issue by lamby** [gplessis/dotdeb-redis#10]
Hi,
Sorry for the strange question but why does this package exist given that sid and jessie-backports are kept well up-to-date with upstream?

**Comment by gplessis** [comment]
Hi Chris,

Redis backports on Dotdeb exist for a while, because such an effort wasn't present in the official Debian repositories.

But now that you maintain such backports for the stable distribution too, I'll be able to discontinue them on Dotdeb (I'll keep maintaining the current branches according to your work to not disrupt existing installations, but I won't create new branches) and contribute to your work whenever needed. Is it ok for you?

Last but not least, thank you very much for your great work on the Debian packages and their backports 👍

**Comment by lamby** [comment]
> Redis backports on Dotdeb exist for a while, because such an effort wasn't present in the official Debian repositories.

Could you elaborate? I can see on:

http://metadata.ftp-master.debian.org/changelogs/main/r/redis/redis_2.8.17-1~bpo70+2_changelog

… that I made the first upload to backports in August 2013.

**Comment by gplessis** [comment]
@lamby you're right, I just didn't notice them back then, I should have stopped duplicating the effort in 2013 and only maintain [those for Squeeze](https://www.dotdeb.org/2011/03/06/redis-updated-to-version-2-2-2/). I can understand your frustration and I'm sorry for that.

Our options here : 
1. Dotdeb keeps maintaining Redis backports for Wheezy and Jessie but won't provide any backport for future Debian releases.
2. Remove any Redis package for Jessie from Dotdeb after a announcement. Users migrate to jessie-backports and any *-backports for future Debian releases. Dotdeb keeps backporting for Wheezy.
3. Remove any Redis package for Jessie and Wheezy from Dotdeb after a announcement. Jessie users migrate to jessie-backports and any *-backports for future Debian releases. Wheezy users are stuck to the 3.2.5 version

What would you prefer? (3. is a bit rough and risky for Wheezy users imho)

**Comment by lamby** [comment]
I'd personally go for 3. I mean, given that wheezy is now in LTS mode, I'd recommend just dropping support for it, especially the kind of outfit using Redis (ie. "newish" tech to some degree) is rather unlikely to be using it in a big way. I'd think differently if it were, say, nginx or something a bit more standard.

(The only frustration is the duplication of effort really, or that my efforts weren't seen on the outside. Also, getting bug reports for dotdeb packages.. ;) )

**Comment by gplessis** [comment]
I'll take action soon and make sure that Dotdeb users can migrate seamlessly. Thanks again for your great work maintaining the packages.

**Comment by gplessis** [comment]
I'll keep releasing Redis 3.2 packages in case maintenance versions are released. But I won't provide Redis 4.0+ since you're already working on providing it on stretch-backports - any plan for jessie-backports?

Thanks for opening this issue and for your outstanding work packaging Redis for any Debian version.

**Comment by lamby** [comment]
@gplessis I don't plan to continue backports to jessie/oldstable. It might make sense now but to keep on top of it for the entire release (ie. for 18 months) seems a little excessive. :)
